version: '3.7'

services:
  nba-frontend: 
    image: 'nba-frontend:1.0.0'
    container_name: nba-frontend
    build: .
    ports:
      - '4200:4200'
      - '49153:49153'
    volumes:
      # - "/app/node_modules"
      - '.:/app'
    environment:
      - COMPOSE_HTTP_TIMEOUT=200
  nba-backend:
    image: 'nba-backend:1.0.0'
    container_name: 'nba-backend'
    ports:
      - '3000:3000'
